"""ScamShield — Threat Intelligence & Cyber Crime Prevention Directory.

Contains verified threat intel on top scam schemes in South Asia/India,
emergency helplines (1930), and immediate victim response guides.
All threat data and statistics are cross-referenced with official bulletins from
the Ministry of Home Affairs (MHA), Indian Cybercrime Coordination Centre (I4C),
CERT-In, and the Reserve Bank of India (RBI).
"""

from __future__ import annotations

# ── Emergency Hotlines & Portals ──────────────────────────────────────────────
EMERGENCY_CONTACTS = [
    {
        "name": "National Cyber Crime Helpline",
        "name_hi": "राष्ट्रीय साइबर अपराध हेल्पलाइन",
        "name_gu": "રાષ્ટ્રીય સાયબર ક્રાઈમ હેલ્પલાઇન",
        "number": "1930",
        "desc": "24x7 toll-free helpline by Ministry of Home Affairs (MHA/I4C) for rapid financial fraud freezing within golden hour.",
        "desc_hi": "वित्तीय धोखाधड़ी की तुरंत रोकथाम के लिए 24x7 टोल-फ्री हेल्पलाइन (गोल्डन ऑवर रिपोर्टिंग)।",
        "desc_gu": "નાણાકીય છેતરપિંડી રોકવા માટે 24x7 ટોલ-ફ્રી હેલ્પલાઇન (ગોલ્ડન અવર રિપોર્ટિંગ).",
        "url": "https://cybercrime.gov.in",
        "badge": "🚨 24x7 Emergency",
    },
    {
        "name": "National Cyber Crime Reporting Portal",
        "name_hi": "राष्ट्रीय साइबर अपराध रिपोर्टिंग पोर्टल",
        "name_gu": "રાષ્ટ્રીય સાયબર ક્રાઈમ રિપોર્ટિંગ પોર્ટલ",
        "number": "cybercrime.gov.in",
        "desc": "Official Government of India portal to register e-FIR for financial fraud, extortion, and cyber crimes.",
        "desc_hi": "वित्तीय धोखाधड़ी और साइबर अपराधों के लिए ऑनलाइन शिकायत दर्ज करने का आधिकारिक पोर्टल।",
        "desc_gu": "નાણાકીય છેતરપિંડી અને સાયબર ગુનાઓ માટે ઓનલાઇન ફરિયાદ નોંધવાનું સત્તાવાર પોર્ટલ.",
        "url": "https://cybercrime.gov.in",
        "badge": "🏛️ Official Portal",
    },
    {
        "name": "Chakshu Portal (Sanchar Saathi)",
        "name_hi": "चक्षु पोर्टल (संचार साथी)",
        "name_gu": "ચક્ષુ પોર્ટલ (સંચાર સાથી)",
        "number": "sancharsaathi.gov.in",
        "desc": "Department of Telecom (DoT) portal to report fraudulent calls, suspicious SMS, and WhatsApp spam.",
        "desc_hi": "धोखाधड़ी वाली कॉल्स, संदिग्ध एसएमएस और व्हाट्सएप स्पैम की रिपोर्ट करने के लिए दूरसंचार विभाग का पोर्टल।",
        "desc_gu": "છેતરપિંડીવાળા કોલ્સ, શંકાસ્પદ એસએમએસ અને વ્હોટ્સએપ સ્પામની જાણ કરવા માટેનું પોર્ટલ.",
        "url": "https://sancharsaathi.gov.in/sfc/",
        "badge": "📞 Telecom Shield",
    },
    {
        "name": "RBI Sachet Portal",
        "name_hi": "आरबीआई सचेत पोर्टल",
        "name_gu": "આરબીઆઈ સचेत पोर्टल",
        "number": "sachet.rbi.org.in",
        "desc": "Reserve Bank of India portal to report illegal deposit schemes, fake NBFCs, and unregistered loan apps.",
        "desc_hi": "अवैध ऋण ऐप्स और अनधिकृत वित्तीय योजनाओं की रिपोर्ट करने के लिए आरबीआई का पोर्टल।",
        "desc_gu": "ગેરકાયદેસર લોન એપ્સ અને અનધિકૃત યોજનાઓની જાણ કરવા માટેનું આરબીઆઈ પોર્ટલ.",
        "url": "https://sachet.rbi.org.in",
        "badge": "🏦 Banking Vigilance",
    },
]

# ── Rampant Scam Patterns in India (Verified Government & Police Data) ──────────
SCAM_TRENDS = [
    {
        "id": "digital_arrest",
        "title": "Digital Arrest Scam",
        "title_hi": "डिजिटल अरेस्ट स्कैम",
        "title_gu": "ડિજિટલ એરેસ્ટ સ્કૅમ",
        "severity": "CRITICAL",
        "source": "MHA / I4C High-Level Committee & Supreme Court Advisory",
        "stat": "₹1,750+ Crores stolen in 2024 • 7,000+ FIRs across India",
        "landmark_case": "Vardhman Group Chairman extorted ₹10.3 Cr; Supreme Court Chief Justice issued public notice warning citizens.",
        "advisory_ref": "https://cybercrime.gov.in",
        "pattern": "Scammers pose as CBI, ED, Police, or Customs via Skype/WhatsApp video calls claiming your Aadhaar or package contains contraband or money laundering funds. They keep victims on continuous video call under 'digital arrest' and demand funds in 'verification escrow accounts'.",
        "pattern_hi": "धोखेबाज सीबीआई, पुलिस या कस्टम्स अधिकारी बनकर वीडियो कॉल करते हैं और आधार से मनी लॉन्ड्रिंग का डर दिखाकर 'जांच' के नाम पर पैसे ट्रांसफर करवाते हैं।",
        "pattern_gu": "સીબીઆઈ અથવા પોલીસ અધિકારી બનીને વીડિયો કોલ દ્વારા ડરાવીને તપાસના નામે પૈસા પડાવવાનો મોટો છેતરપિંડી.",
        "reality_check": "Legitimate law enforcement NEVER conducts arrests or takes statements via WhatsApp or Skype, and NEVER asks for money transfers.",
        "reality_check_hi": "पुलिस या सीबीआई कभी भी व्हाट्सएप/स्काइप पर बयान नहीं लेती और न ही पैसे ट्रांसफर करने को कहती है।",
        "reality_check_gu": "પોલીસ કે સીબીઆઈ ક્યારેય વીડિયો કોલ પર અરેસ્ટ નથી કરતી કે પૈસા માંગતી નથી.",
    },
    {
        "id": "electricity_bill",
        "title": "Electricity Power Cut SMS",
        "title_hi": "बिजली बिल डिस्कनेक्शन एसएमएस",
        "title_gu": "વીજળી બિલ કપાઈ જવાનો એસએમએસ",
        "severity": "HIGH",
        "source": "Ministry of Power & State DISCOMs Public Notice",
        "stat": "Over 45,000 complaints logged on 1930 portal in 2024",
        "landmark_case": "Retired government official in Delhi lost ₹14.8 Lakhs after downloading fake 'Urja Update' APK sent via WhatsApp.",
        "advisory_ref": "https://sancharsaathi.gov.in/sfc/",
        "pattern": "SMS claiming 'Your electricity power will be disconnected tonight at 9:30 PM due to unpaid bill. Immediately contact power officer on 9XXXXXXXXX'. Calling leads to installing remote screen-sharing apps (AnyDesk, TeamViewer) or malicious APKs.",
        "pattern_hi": "मैसेज आता है कि आज रात बिजली कट जाएगी, तुरंत दिए गए नंबर पर कॉल करें। कॉल करने पर स्क्रीन शेयरिंग ऐप डाउनलोड कराई जाती है।",
        "pattern_gu": "સંદેશ આવે છે કે આજે રાત્રે વીજળી કટ થઈ જશે, આપેલ નંબર પર સંપર્ક કરો. કૉલ કરવાથી છેતરપિંડી થાય છે.",
        "reality_check": "DISCOMs send bills from verified headers (e.g., AD-TNEB, VM-BESCOM), never personal 10-digit mobile numbers.",
        "reality_check_hi": "बिजली कंपनियां कभी भी व्यक्तिगत 10 अंकों के मोबाइल नंबर से नोटिस नहीं भेजती हैं।",
        "reality_check_gu": "વીજ કંપનીઓ ક્યારેય પર્સનલ મોબાઈલ નંબરથી બિલ નોટિસ મોકલતી નથી.",
    },
    {
        "id": "task_fraud",
        "title": "Part-Time Job / Telegram Task Fraud",
        "title_hi": "पार्ट-टाइम नौकरी / टेलीग्राम टास्क धोखाधड़ी",
        "title_gu": "પાર્ટ-ટાઇમ જોબ / ટેલિગ્રામ ટાસ્ક ફ્રોડ",
        "severity": "HIGH",
        "source": "ED (Enforcement Directorate) Nationwide Chargesheets & I4C",
        "stat": "₹3,120+ Crores laundered via Southeast Asian scam syndicates",
        "landmark_case": "Tech professional in Bengaluru duped of ₹84 Lakhs over 14 days in fake Google Maps review ratings.",
        "advisory_ref": "https://cybercrime.gov.in",
        "pattern": "Offers to earn ₹2,000-₹8,000 daily by simply rating hotels, liking YouTube videos, or reviewing products. Small initial payments (₹150-₹500) build trust before asking users to deposit large sums in 'prepaid high-yield tasks'.",
        "pattern_hi": "यूट्यूब वीडियो लाइक करके या होटल रेटिंग देकर रोज हजारों रुपये कमाने का झांसा। बाद में 'प्रीमियम टास्क' के नाम पर लाखों रुपये ठग लिए जाते हैं।",
        "pattern_gu": "યુટ્યુબ લાઈક કે રિવ્યૂ આપીને રોજના હજારો કમાવવાની લાલચ આપીને લાખો રૂપિયા પડાવી લેવામાં આવે છે.",
        "reality_check": "No legitimate enterprise pays high wages for liking videos or requires you to deposit money to withdraw earned income.",
        "reality_check_hi": "कोई भी वास्तविक कंपनी वीडियो लाइक करने के लिए पैसे नहीं देती और न ही पैसे निकालने के लिए पैसे मांगती है।",
        "reality_check_gu": "કોઈપણ સાચી કંપની વીડિયો લાઈક કરવા માટે પૈસા નથી આપતી.",
    },
    {
        "id": "upi_screen_share",
        "title": "UPI Refund / Collect Request Trap",
        "title_hi": "UPI रिफंड / स्क्रीन शेयरिंग फ्रॉड",
        "title_gu": "UPI રિફંડ / કલેક્ટ રિકવેસ્ટ ટ્રેપ",
        "severity": "CRITICAL",
        "source": "NPCI (National Payments Corporation of India) & RBI Advisory",
        "stat": "48% of digital payment disputes in India involve deceptive Collect Requests",
        "landmark_case": "Merchant in Pune lost ₹4.5 Lakhs when fraudster sent 'Collect Request' disguised as incoming customer payment.",
        "advisory_ref": "https://www.npci.org.in",
        "pattern": "Fraudsters send a 'Collect Request' on PhonePe/GPay claiming it is a 'Cashback' or 'Refund'. They tell the victim: 'Enter your UPI PIN to receive payment.'",
        "pattern_hi": "धोखेबाज PhonePe या GPay पर 'कलेक्ट रिक्वेस्ट' भेजते हैं और कहते हैं कि कैशबैक पाने के लिए अपना UPI पिन डालें।",
        "pattern_gu": "કેશબેક કે રિફંડ આપવાના બહાને રિકવેસ્ટ મોકલીને UPI પિન દાખલ કરાવીને પૈસા ઉપાડી લે છે.",
        "reality_check": "GOLDEN RULE: You NEVER need to enter your UPI PIN to RECEIVE money. Entering PIN ALWAYS DEBITS money.",
        "reality_check_hi": "याद रखें: पैसे प्राप्त करने के लिए कभी भी UPI PIN दर्ज करने की आवश्यकता नहीं होती। PIN डालने से हमेशा पैसे कटते हैं।",
        "reality_check_gu": "યાદ રાખો: પૈસા મેળવવા માટે ક્યારેય UPI PIN નાખવો પડતો નથી. પિન નાખવાથી હંમેશા પૈસા કપાય છે.",
    },
    {
        "id": "fedex_customs",
        "title": "FedEx / Courier Narcotic Drugs Scam",
        "title_hi": "फेडेक्स कूरियर / ड्रग्स पार्सल स्कैम",
        "title_gu": "ફેડેક્સ કુરિયર / ડ્રગ્સ પાર્સલ સ્કૅમ",
        "severity": "HIGH",
        "source": "Narcotics Control Bureau (NCB) & FedEx Official Alert",
        "stat": "Over 2,400 senior citizens targeted in metro cities (2023-2024)",
        "landmark_case": "Retired physician in Mumbai duped of ₹1.97 Crores under threat of immediate arrest by fake NCB narcotics officer.",
        "advisory_ref": "https://cybercrime.gov.in",
        "pattern": "Automated call stating 'A FedEx parcel sent by you to Taiwan/Dubai contains 5 passports and 140g MDMA drugs. Press 1 to speak with Narcotics Bureau.'",
        "pattern_hi": "कॉल आता है कि आपके नाम से विदेश जा रहे पार्सल में ड्रग्स पकड़े गए हैं और आपको पुलिस/नारकोटिक्स से डराया जाता है।",
        "pattern_gu": "કોલ આવે છે કે તમારા પાર્સલમાં ડ્રગ્સ પકડાયા છે અને પોલીસના નામે ડરાવીને પૈસા પડાવે છે.",
        "reality_check": "Courier services cannot transfer calls to police, and law enforcement does not ask for settlement money to clear names.",
        "reality_check_hi": "कूरियर कंपनियाँ कभी भी पुलिस को कॉल ट्रांसफर नहीं कर सकतीं।",
        "reality_check_gu": "કુરિયર કંપનીઓ ક્યારેય પોલીસને સીધો કોલ ટ્રાન્સફર કરતી નથી.",
    },
    {
        "id": "fake_loan_apk",
        "title": "Instant Loan App APK Harassment",
        "title_hi": "फर्जी लोन ऐप APK ब्लैकमेलिंग",
        "title_gu": "ફેક લોન એપ APK હેરાનગતિ",
        "severity": "CRITICAL",
        "source": "RBI White List & Google Play Safety Enforcement",
        "stat": "3,500+ illegal loan apps removed; ₹120+ Cr frozen across payment gateways",
        "landmark_case": "ED multi-city raid dismantles predatory lending syndicate running fake Chinese-backed NBFC shell entities.",
        "advisory_ref": "https://sachet.rbi.org.in",
        "pattern": "Unregistered instant loan apps downloaded from links (not Play Store). During installation they steal contacts, gallery photos, and location, then morph photos and blackmail relatives for 300% interest repayment.",
        "pattern_hi": "अनधिकृत लोन ऐप्स फोन के कॉन्टैक्ट्स और फोटो चुरा लेते हैं और रिश्तेदारों को मॉर्फ्ड फोटो भेजकर ब्लैकमेल करते हैं।",
        "pattern_gu": "ગેરકાયદે લોન એપ્સ ડાઉનલોડ કરાવીને કોન્ટેક્ટ અને ફોટો ચોરીને સંબંધીઓને બ્લેકમેલ કરે છે.",
        "reality_check": "Only borrow from RBI-registered NBFCs and banks listed on the RBI website. Never sideload .apk files from WhatsApp/SMS.",
        "reality_check_hi": "केवल RBI पंजीकृत बैंकों और NBFC से ही ऋण लें। कभी भी किसी अज्ञात लिंक से .apk फ़ाइल इंस्टॉल न करें।",
        "reality_check_gu": "માત્ર RBI માન્ય બેંકોમાંથી જ લોન લો. ક્યારેય કોઈ અજાણી .apk ફાઇલ ઇન્સ્ટોલ ન કરો.",
    },
    {
        "id": "investment_trading",
        "title": "Fake Stock Trading / Pig Butchering",
        "title_hi": "फर्जी शेयर ट्रेडिंग / पिग बुचरिंग स्कैम",
        "title_gu": "નકલી શેર ટ્રેડિંગ / પિગ બુચરિંગ સ્કેમ",
        "severity": "CRITICAL",
        "source": "SEBI Investor Caution Notice PR No. 04/2024 & I4C",
        "stat": "₹4,200+ Crores lost by Indian retail investors in fake FII trading apps (2024)",
        "landmark_case": "Businessman in Hyderabad defrauded of ₹5.2 Crores via fake 'Goldman Sachs Institutional VIP' WhatsApp group.",
        "advisory_ref": "https://www.sebi.gov.in",
        "pattern": "Victims are lured into WhatsApp/Telegram groups by fake institutional advisors claiming 20-50% guaranteed weekly profits. They install customized fake trading apps showing simulated balances. When attempting to withdraw, scammers demand high 'tax' and 'clearance fees' before vanishing.",
        "pattern_hi": "टेलीग्राम या व्हाट्सएप पर 'विशेषज्ञ' बनकर 20-50% मुनाफे का झांसा देते हैं। फर्जी ऐप में मुनाफा दिखता है पर निकासी के समय लाखों रुपये टैक्स के नाम पर मांगकर गायब हो जाते हैं।",
        "pattern_gu": "વોટ્સએપ/ટેલિગ્રામ પર ગેરેન્ટેડ નફાની લાલચ આપીને નકલી એપ્સ દ્વારા રોકાણ કરાવી પૈસા પડાવી લે છે.",
        "reality_check": "SEBI-registered brokers NEVER promise guaranteed returns and never operate exclusively out of anonymous WhatsApp/Telegram channels.",
        "reality_check_hi": "SEBI-पंजीकृत कोई भी ब्रोकर कभी भी गारंटीड रिटर्न का वादा नहीं कर सकता।",
        "reality_check_gu": "SEBI માન્ય કોઈ પણ બ્રોકર ક્યારેય ગેરેન્ટેડ નફો આપવાનો વાયદો નથી કરતા.",
    },
    {
        "id": "sim_swap",
        "title": "SIM Swap & Porting Fraud",
        "title_hi": "सिम स्वैप एवं पोर्टिंग धोखाधड़ी",
        "title_gu": "સિમ સ્વેપ અને પોર્ટિંગ ફ્રોડ",
        "severity": "HIGH",
        "source": "DoT & TRAI Mandatory 7-Day SMS Freeze Regulation (July 2024)",
        "stat": "TRAI instituted mandatory 7-day port cooldown post SIM swap to prevent OTP interception",
        "landmark_case": "Textile exporter lost ₹1.1 Crores at midnight after SIM suddenly went inactive due to fraudulent replacement.",
        "advisory_ref": "https://sancharsaathi.gov.in",
        "pattern": "Fraudsters obtain personal Aadhaar/ID info and trick telecom stores or victims into approving a SIM upgrade or port request. Once the victim's phone loses network, the scammer receives all 2FA OTPs and drains bank accounts.",
        "pattern_hi": "धोखेबाज फर्जी दस्तावेजों से आपके नंबर की नई सिम निकलवा लेते हैं। फोन का नेटवर्क जाते ही वे आपके सारे OTP पाकर बैंक खाता खाली कर देते हैं।",
        "pattern_gu": "નકલી દસ્તાવેજોથી તમારું સિમ કાર્ડ અન્ય વ્યક્તિના નામે ચાલુ કરાવીને બેંક ખાતામાંથી પૈસા ઉપાડી લે છે.",
        "reality_check": "If your phone suddenly shows 'No Service' unexpectedly, contact your telecom operator immediately from another phone.",
        "reality_check_hi": "यदि आपका फोन अचानक बिना वजह नेटवर्क खो दे, तो तुरंत दूसरे फोन से अपने टेलीकॉम ऑपरेटर से संपर्क करें।",
        "reality_check_gu": "જો ફોનમાં અચાનક નેટવર્ક જતું રહે, તો તરત જ કંપનીનો સંપર્ક કરો.",
    },
    {
        "id": "deepfake_cloning",
        "title": "AI Deepfake Voice & Video Distress Call",
        "title_hi": "AI डीपफेक वॉयस एवं वीडियो कॉल फ्रॉड",
        "title_gu": "AI ડીપફેક વોઈસ અને વિડીયો કોલ ફ્રોડ",
        "severity": "CRITICAL",
        "source": "CERT-In Cyber Advisory on Generative AI Fraud & MeitY Guidelines",
        "stat": "300% surge in synthetic voice cloning cases reported to state cyber cells in 2024",
        "landmark_case": "Senior citizen in Kozhikode paid ₹40,000 after video call from a deepfake clone of his former colleague in Dubai.",
        "advisory_ref": "https://cert-in.org.in",
        "pattern": "Scammers harvest short voice samples from social media reels and synthesize a distressed family member's voice saying 'I had a car accident / police arrested me, send ₹50,000 urgently'.",
        "pattern_hi": "सोशल मीडिया से आवाज चुराकर AI से हूबहू वैसी आवाज बनाकर परिजन के नाम पर इमरजेंसी में तुरंत पैसे भेजने की मांग करते हैं।",
        "pattern_gu": "સોશિયલ મીડિયા પરથી અવાજ ક્લોન કરીને અકસ્માત કે જેલના નામે તાત્કાલિક પૈસા પડાવવાનો નવો સ્કેમ.",
        "reality_check": "Always hang up and call the family member back on their known number or test with an agreed family safe-word.",
        "reality_check_hi": "हमेशा फोन काटें और परिजन के वास्तविक नंबर पर दोबारा कॉल करके पुष्टि करें।",
        "reality_check_gu": "તરત ફોન કાપીને તમારા પરિચિત નંબર પર ફરીથી કોલ કરીને ખરાઈ કરો.",
    },
    {
        "id": "whatsapp_business_impersonation",
        "title": "Verified Business Brand Impersonation",
        "title_hi": "ब्रांड एवं कस्टमर केयर प्रतिरूपण",
        "title_gu": "કંપની કસ્ટમર કેર નકલી પ્રોફાઇલ ફ્રોડ",
        "severity": "HIGH",
        "source": "TRAI Directive on Unregistered Telemarketers & Chakshu Registry",
        "stat": "Over 1.8 Crore mobile connections disconnected by DoT for spam & impersonation (2024)",
        "landmark_case": "Fake Emirates & Indigo flight refund profiles cheated travelers of ₹68 Lakhs during monsoon cancellations.",
        "advisory_ref": "https://sancharsaathi.gov.in/sfc/",
        "pattern": "Scammers create accounts with company logos and fake green/blue verification badges, contacting people with fake parcel tracking issues, credit card reward expiry, or airline refunds.",
        "pattern_hi": "कंपनी के लोगो और फर्जी वेरिफिकेशन टिक का उपयोग करके क्रेडिट कार्ड रिवॉर्ड पॉइंट्स या पार्सल के नाम पर ठगी की जाती है।",
        "pattern_gu": "ઓફિશિયલ બ્રાન્ડના નામે ગિફ્ટ કે ક્રેડિટ કાર્ડ રિવોર્ડ એક્સપાયરીના બહાને ઓટીપી ચોરી લે છે.",
        "reality_check": "Legitimate brands will never ask you to pay fees to claim reward points or share debit card CVV/OTP over WhatsApp.",
        "reality_check_hi": "कोई भी असली कंपनी रिवॉर्ड पॉइंट्स के लिए पैसे या OTP कभी नहीं मांगती।",
        "reality_check_gu": "કોઈપણ સાચી કંપની રિવોર્ડ કે કેશબેક માટે OTP નથી માંગતી.",
    },
    {
        "id": "romance_honeytrap",
        "title": "Matrimonial & Romance Honeytrap",
        "title_hi": "मैट्रिमोनियल एवं सोशल मीडिया हनीट्रैप",
        "title_gu": "મેટ્રિમોનિયલ અને હનીટ્રેપ સ્કેમ",
        "severity": "HIGH",
        "source": "Delhi Police Cyber Crime Unit & Matrimonial Fraud Special Cells",
        "stat": "Over ₹150 Crores reported lost in cross-border matrimonial extortion schemes",
        "landmark_case": "Software engineer in Gurugram duped of ₹36 Lakhs for 'Customs Clearance duty' for UK luxury gift parcel.",
        "advisory_ref": "https://cybercrime.gov.in",
        "pattern": "Scammer poses as a high-earning NRI or foreigner on dating/matrimony sites. After building emotional trust over weeks, they claim to send expensive gifts held at airport customs requiring 'clearance duty' payment.",
        "pattern_hi": "विवाह या डेटिंग साइट्स पर एनआरआई बनकर विश्वास जीतते हैं और फिर 'कस्टम्स में गिफ्ट फंसने' के नाम पर लाखों रुपये ऐंठते हैं।",
        "pattern_gu": "લગ્ન અથવા ડેટિંગ સાઈટ પર વિદેશી કે NRI બનીને વિશ્વાસ કેળવી કસ્ટમ ડ્યુટીના નામે છેતરપિંડી કરે છે.",
        "reality_check": "Indian Customs NEVER asks individuals to deposit customs duty into personal savings accounts via UPI.",
        "reality_check_hi": "भारतीय कस्टम्स कभी भी किसी व्यक्ति के व्यक्तिगत बैंक खाते में ड्यूटी जमा करने को नहीं कहता।",
        "reality_check_gu": "કસ્ટમ વિભાગ ક્યારેય વ્યક્તિગત ખાતામાં ડ્યુટી ટ્રાન્સફર કરવાનું કહેતું નથી.",
    },
    {
        "id": "marketplace_buyer",
        "title": "OLX / Marketplace Army Officer Scam",
        "title_hi": "OLX / मार्केटप्लेस आर्मी ऑफिसर स्कैम",
        "title_gu": "OLX આર્મી ઓફિસર સ્કેમ",
        "severity": "MEDIUM",
        "source": "Indian Army Cyber Security Cell & Cyber Dost (MHA)",
        "stat": "Over 20,000 fake military ID fraud cases recorded across online marketplaces",
        "landmark_case": "College professor in Jaipur selling sofa on OLX lost ₹1.2 Lakhs via fraudulent Army Officer QR collect scam.",
        "advisory_ref": "https://cybercrime.gov.in",
        "pattern": "Scammer poses as an Army/Defence officer getting transferred and willing to buy your listed item immediately without negotiation. They send a fake UPI collect QR code saying 'Scan and enter PIN to accept my payment'.",
        "pattern_hi": "आर्मी ऑफिसर का फर्जी आईडी कार्ड दिखाकर सामान तुरंत खरीदने का झांसा देते हैं और पैसे देने के नाम पर UPI QR कोड से पैसे उड़ा लेते हैं।",
        "pattern_gu": "આર્મી ઓફિસર બનીને ખરીદીની તૈયારી બતાવી કલેક્ટ રિકવેસ્ટ દ્વારા ખાતું ખાલી કરી નાખે છે.",
        "reality_check": "Remember: Scanning a QR code or entering your UPI PIN ALWAYS debits money from your account, never credits it.",
        "reality_check_hi": "याद रखें: QR कोड स्कैन करने या PIN डालने से हमेशा पैसे कटते हैं, कभी क्रेडिट नहीं होते।",
        "reality_check_gu": "યાદ રાખો: QR કોડ સ્કેન કરવાથી પૈસા કપાય છે, જમા નથી થતા.",
    },
]

# ── Victim Golden Hour Recovery Protocol ───────────────────────────────────────
GOLDEN_HOUR_STEPS = [
    {
        "step": "1. Call 1930 Immediately",
        "step_hi": "1. तुरंत 1930 पर कॉल करें",
        "step_gu": "1. તાત્કાલિક 1930 પર કૉલ કરો",
        "detail": "Within the first 2-3 hours ('Golden Hour'), the I4C portal can freeze the recipient scammer's bank/wallet account before money is withdrawn at an ATM.",
        "detail_hi": "पहले 2-3 घंटों के भीतर 1930 पर कॉल करने से पुलिस फ्रॉड खाते को तुरंत फ्रीज करवा सकती है।",
        "detail_gu": "પહેલા 2-3 કલાકમાં 1930 પર કોલ કરવાથી ફ્રોડ બેંક ખાતું તાત્કાલિક ફ્રીઝ થઈ શકે છે.",
    },
    {
        "step": "2. Contact Your Bank / UPI App",
        "step_hi": "2. अपने बैंक और UPI ऐप से संपर्क करें",
        "step_gu": "2. તમારી બેંક અને UPI એપનો સંપર્ક કરો",
        "detail": "Block debit/credit cards, report fraudulent UPI transaction ID (UTR number), and request an immediate chargeback/fraud flag.",
        "detail_hi": "अपने कार्ड ब्लॉक करें, UPI ट्रांजैक्शन आईडी (UTR नंबर) नोट करें और बैंक को सूचित करें।",
        "detail_gu": "કાર્ડ બ્લોક કરો, UPI ટ્રાન્ઝેક્શન આઈડી નોંધીને બેંકને તાત્કાલિક જાણ કરો.",
    },
    {
        "step": "3. File Official e-FIR at cybercrime.gov.in",
        "step_hi": "3. cybercrime.gov.in पर e-FIR दर्ज करें",
        "step_gu": "3. cybercrime.gov.in પર e-FIR નોંધાવો",
        "detail": "Take screenshots of chat history, payment receipts, phone numbers, and submit a complete formal cyber complaint.",
        "detail_hi": "चैट के स्क्रीनशॉट, पेमेंट रसीद और फोन नंबर संभाल कर रखें और ऑनलाइन रिपोर्ट दर्ज करें।",
        "detail_gu": "ચેટના સ્ક્રીનશોટ, પેમેન્ટ રસીદ અને ફોન નંબર સાથે ઓનલાઇન ફરિયાદ દાખલ કરો.",
    },
    {
        "step": "4. Disconnect Remote Apps & Reset Passwords",
        "step_hi": "4. रिमोट ऐप्स अनइंस्टॉल करें और पासवर्ड बदलें",
        "step_gu": "4. રીમોટ એપ્સ અનઇન્સ્ટોલ કરો અને પાસવર્ડ બદલો",
        "detail": "If you installed AnyDesk, RustDesk, or suspicious APKs, turn off internet/Wi-Fi immediately, uninstall the apps, and reset net banking passwords on another device.",
        "detail_hi": "यदि कोई स्क्रीन शेयरिंग ऐप डाउनलोड की हो तो इंटरनेट बंद करके उसे तुरंत डिलीट करें और पासवर्ड बदलें।",
        "detail_gu": "જો કોઈ શંકાસ્પદ એપ ઇન્સ્ટોલ કરી હોય તો તરત ઇન્ટરનેટ બંધ કરી એપ ડીલીટ કરો.",
    },
]
