"""ScamShield — Scam Awareness Quiz Data.

45 questions covering UPI safety, Digital Arrest, KYC fraud, OTP rules,
Deepfakes, Loan APK, Job scams, QR codes, and more — for India context.
"""
from __future__ import annotations

# ── Quiz Questions ─────────────────────────────────────────────────────────────
QUIZ_QUESTIONS: list[dict] = [

    # ── BEGINNER (1-15) ────────────────────────────────────────────────────────
    {
        "id": "b1",
        "difficulty": "beginner",
        "category": "UPI Safety",
        "question_en": "Do you need to enter your UPI PIN to RECEIVE money from someone?",
        "question_hi": "क्या पैसे प्राप्त करने के लिए आपको अपना UPI PIN डालना होता है?",
        "options": [
            {"text": "Yes, always enter PIN to receive money", "text_hi": "हाँ, पैसे पाने के लिए हमेशा PIN डालें", "is_correct": False},
            {"text": "No, you NEVER need PIN to receive money — only to send", "text_hi": "नहीं, पैसे पाने के लिए PIN की जरूरत नहीं — सिर्फ भेजने के लिए", "is_correct": True},
            {"text": "Only for amounts above ₹5,000", "text_hi": "केवल ₹5,000 से ऊपर की राशि के लिए", "is_correct": False},
            {"text": "Only when receiving from unknown contacts", "text_hi": "केवल अजनबी से पैसे लेते समय", "is_correct": False},
        ],
        "explanation_en": "GOLDEN RULE: Entering your UPI PIN always DEBITS money. You never need PIN to receive. Scammers trick you into entering PIN saying it's for a 'refund' or 'cashback'.",
        "explanation_hi": "याद रखें: UPI PIN डालने से हमेशा पैसे कटते हैं, आते नहीं। धोखेबाज 'कैशबैक' के नाम पर PIN मंगवाते हैं।",
        "points": 10,
    },
    {
        "id": "b2",
        "difficulty": "beginner",
        "category": "OTP Safety",
        "question_en": "A bank employee calls asking for your OTP to 'verify your account'. What should you do?",
        "question_hi": "एक बैंक कर्मचारी आपका OTP मांग रहा है 'खाता सत्यापित' करने के लिए। आप क्या करेंगे?",
        "options": [
            {"text": "Give OTP since it's a bank employee", "text_hi": "OTP दें क्योंकि वो बैंक का कर्मचारी है", "is_correct": False},
            {"text": "Give only the last 4 digits", "text_hi": "केवल अंतिम 4 अंक दें", "is_correct": False},
            {"text": "NEVER share OTP — real banks never ask for it", "text_hi": "OTP कभी शेयर न करें — असली बैंक कभी नहीं मांगता", "is_correct": True},
            {"text": "Share OTP but change it immediately after", "text_hi": "OTP दें और तुरंत बदल लें", "is_correct": False},
        ],
        "explanation_en": "No bank, government agency, or company will EVER ask for your OTP over the phone. OTPs are single-use security codes — sharing them gives fraudsters full access.",
        "explanation_hi": "कोई भी बैंक या सरकारी संस्था कभी OTP नहीं मांगती। OTP शेयर करने से धोखेबाजों को आपके खाते तक पूरी पहुँच मिल जाती है।",
        "points": 10,
    },
    {
        "id": "b3",
        "difficulty": "beginner",
        "category": "Digital Arrest",
        "question_en": "A person on WhatsApp video call claims to be a CBI officer and says you are 'digitally arrested'. What is this?",
        "question_hi": "WhatsApp पर वीडियो कॉल पर कोई CBI अधिकारी बनकर कह रहा है आप 'डिजिटल अरेस्ट' हैं। यह क्या है?",
        "options": [
            {"text": "A real CBI investigation you must comply with", "text_hi": "एक असली CBI जांच जिसमें सहयोग करना जरूरी है", "is_correct": False},
            {"text": "A scam — law enforcement NEVER arrests via WhatsApp", "text_hi": "एक धोखाधड़ी — पुलिस WhatsApp पर गिरफ्तार नहीं करती", "is_correct": True},
            {"text": "A new government digital identity verification", "text_hi": "एक नई सरकारी डिजिटल पहचान सत्यापन प्रक्रिया", "is_correct": False},
            {"text": "A legal court notice delivered digitally", "text_hi": "डिजिटल रूप से दिया गया अदालत का नोटिस", "is_correct": False},
        ],
        "explanation_en": "Digital Arrest is India's #1 scam of 2025-26. No law in India allows 'digital arrest'. Real CBI/Police NEVER conduct investigations or make arrests via WhatsApp or Skype.",
        "explanation_hi": "डिजिटल अरेस्ट 2025-26 का सबसे बड़ा घोटाला है। भारत में ऐसा कोई कानून नहीं। CBI कभी WhatsApp पर जांच नहीं करती।",
        "points": 10,
    },
    {
        "id": "b4",
        "difficulty": "beginner",
        "category": "SMS Safety",
        "question_en": "You receive SMS: 'Your SBI account will be blocked in 24 hours. Click bit.ly/sbi-kyc to update KYC'. What should you do?",
        "question_hi": "SMS आता है: 'आपका SBI खाता 24 घंटों में बंद होगा। KYC अपडेट करें bit.ly/sbi-kyc पर।' आप क्या करेंगे?",
        "options": [
            {"text": "Click the link and update KYC", "text_hi": "लिंक पर क्लिक करें और KYC अपडेट करें", "is_correct": False},
            {"text": "Ignore — shortened URLs from banks are always scams", "text_hi": "अनदेखा करें — बैंक कभी शॉर्टन्ड URL नहीं भेजते", "is_correct": True},
            {"text": "Forward to bank customer care", "text_hi": "बैंक कस्टमर केयर को फॉरवर्ड करें", "is_correct": False},
            {"text": "Visit the link only on desktop, not mobile", "text_hi": "लिंक केवल डेस्कटॉप पर खोलें, मोबाइल पर नहीं", "is_correct": False},
        ],
        "explanation_en": "Real banks NEVER send shortened URLs (bit.ly, tinyurl). If you need to update KYC, always visit the official bank website directly by typing the URL yourself.",
        "explanation_hi": "असली बैंक कभी bit.ly जैसे शॉर्ट लिंक नहीं भेजते। KYC अपडेट के लिए सीधे बैंक की वेबसाइट टाइप करके जाएं।",
        "points": 10,
    },
    {
        "id": "b5",
        "difficulty": "beginner",
        "category": "QR Code",
        "question_en": "A buyer on OLX asks you to scan their QR code to 'receive payment'. What will actually happen?",
        "question_hi": "OLX पर खरीदार आपसे QR कोड स्कैन करने को कह रहा है 'पैसे पाने के लिए'। असल में क्या होगा?",
        "options": [
            {"text": "You will receive the payment safely", "text_hi": "आपको सुरक्षित रूप से पैसे मिलेंगे", "is_correct": False},
            {"text": "Money will be DEDUCTED from your account, not added", "text_hi": "आपके खाते से पैसे कटेंगे, आएंगे नहीं", "is_correct": True},
            {"text": "Nothing will happen until you confirm OTP", "text_hi": "OTP कन्फर्म करने तक कुछ नहीं होगा", "is_correct": False},
            {"text": "Only the buyer's bank details will be shared with you", "text_hi": "केवल खरीदार के बैंक विवरण आपके साथ शेयर होंगे", "is_correct": False},
        ],
        "explanation_en": "QR codes for PAYMENT always deduct money. You NEVER need to scan a QR code to RECEIVE money. The buyer sends a payment request QR to take money FROM you.",
        "explanation_hi": "QR कोड स्कैन करने से पैसे कटते हैं, आते नहीं। पैसे पाने के लिए QR कोड स्कैन करने की जरूरत नहीं होती।",
        "points": 10,
    },
    {
        "id": "b6",
        "difficulty": "beginner",
        "category": "Loan Apps",
        "question_en": "A loan app asks permission to access your contacts and gallery photos during installation. What should you do?",
        "question_hi": "एक लोन ऐप इंस्टॉल करते समय आपके कॉन्टैक्ट्स और गैलरी फोटो तक पहुँच मांग रहा है। क्या करें?",
        "options": [
            {"text": "Grant permissions — it's normal for loan verification", "text_hi": "अनुमति दें — लोन वेरिफिकेशन के लिए जरूरी है", "is_correct": False},
            {"text": "Immediately uninstall — this is a predatory loan app", "text_hi": "तुरंत अनइंस्टॉल करें — यह शिकारी लोन ऐप है", "is_correct": True},
            {"text": "Grant only contacts permission, not gallery", "text_hi": "केवल कॉन्टैक्ट्स की अनुमति दें, गैलरी की नहीं", "is_correct": False},
            {"text": "It's safe if installed from Play Store", "text_hi": "Play Store से इंस्टॉल हो तो सुरक्षित है", "is_correct": False},
        ],
        "explanation_en": "Legitimate loan providers (banks/NBFCs) NEVER need your photos or contacts. Predatory loan apps steal this data to blackmail you and your family if you can't repay.",
        "explanation_hi": "असली बैंक या NBFC को आपके कॉन्टैक्ट्स या फोटो की जरूरत नहीं। ये ऐप्स डेटा चुराकर परिवार को ब्लैकमेल करते हैं।",
        "points": 10,
    },
    {
        "id": "b7",
        "difficulty": "beginner",
        "category": "Job Scam",
        "question_en": "You are offered ₹3,000/day to like YouTube videos from home. But first you must deposit ₹2,000 as 'registration'. Is this legitimate?",
        "question_hi": "घर बैठे YouTube वीडियो लाइक करके ₹3,000/दिन कमाने का ऑफर है, पर पहले ₹2,000 'रजिस्ट्रेशन' देना होगा। क्या यह सच है?",
        "options": [
            {"text": "Yes, it's a genuine part-time job opportunity", "text_hi": "हाँ, यह एक असली पार्ट-टाइम अवसर है", "is_correct": False},
            {"text": "No — no legitimate job requires a deposit first", "text_hi": "नहीं — कोई भी असली नौकरी पहले पैसे नहीं मांगती", "is_correct": True},
            {"text": "Only if the company has a website", "text_hi": "केवल तब अगर कंपनी की वेबसाइट हो", "is_correct": False},
            {"text": "It's legitimate if offered via LinkedIn", "text_hi": "LinkedIn पर मिले तो ठीक है", "is_correct": False},
        ],
        "explanation_en": "Task Fraud / Pig Butchering: You are paid small amounts to build trust, then asked for large 'deposits' for premium tasks. These are always lost. Legitimate employers NEVER charge workers.",
        "explanation_hi": "पहले छोटे पैसे देकर भरोसा बनाते हैं, फिर बड़ी रकम मांगते हैं। असली नौकरी में कभी पैसे नहीं देने होते।",
        "points": 10,
    },
    {
        "id": "b8",
        "difficulty": "beginner",
        "category": "Call Safety",
        "question_en": "You get an automated call: 'Your FedEx parcel in Taiwan has 5 passports and 140g drugs. Press 1 for Narcotics Bureau.' What should you do?",
        "question_hi": "ऑटोमेटेड कॉल: 'आपके FedEx पार्सल में ड्रग्स पकड़ी गई। नारकोटिक्स ब्यूरो के लिए 1 दबाएं।' क्या करें?",
        "options": [
            {"text": "Press 1 to speak with the Narcotics Bureau", "text_hi": "1 दबाएं और नारकोटिक्स ब्यूरो से बात करें", "is_correct": False},
            {"text": "Hang up immediately — this is a scam call", "text_hi": "तुरंत फोन काटें — यह धोखाधड़ी की कॉल है", "is_correct": True},
            {"text": "Listen to understand what parcel they mean", "text_hi": "सुनें ताकि पता चले किस पार्सल की बात है", "is_correct": False},
            {"text": "Press 2 to cancel the shipment", "text_hi": "शिपमेंट रद्द करने के लिए 2 दबाएं", "is_correct": False},
        ],
        "explanation_en": "FedEx/Courier Scam: Courier companies cannot transfer calls to police, and law enforcement does not call to offer 'settlements'. Hang up and block the number.",
        "explanation_hi": "कूरियर कंपनियाँ पुलिस को कॉल ट्रांसफर नहीं कर सकतीं। यह डिजिटल अरेस्ट स्कैम का पहला कदम है। कॉल काटें।",
        "points": 10,
    },
    {
        "id": "b9",
        "difficulty": "beginner",
        "category": "Emergency Numbers",
        "question_en": "What is the National Cyber Crime Helpline number in India you should call if you've been scammed?",
        "question_hi": "भारत में साइबर धोखाधड़ी होने पर किस नंबर पर कॉल करें?",
        "options": [
            {"text": "100 (Police)", "text_hi": "100 (पुलिस)", "is_correct": False},
            {"text": "1930 (National Cyber Crime Helpline)", "text_hi": "1930 (राष्ट्रीय साइबर अपराध हेल्पलाइन)", "is_correct": True},
            {"text": "112 (Emergency Services)", "text_hi": "112 (आपातकालीन सेवाएं)", "is_correct": False},
            {"text": "155260 (Bank fraud only)", "text_hi": "155260 (केवल बैंक धोखाधड़ी)", "is_correct": False},
        ],
        "explanation_en": "Call 1930 IMMEDIATELY after a cyber fraud — within 2-3 hours (Golden Hour), authorities can freeze the fraudster's account before they withdraw your money.",
        "explanation_hi": "धोखाधड़ी के 2-3 घंटों में 1930 पर कॉल करें। इस 'गोल्डन ऑवर' में पुलिस धोखेबाज का खाता फ्रीज कर सकती है।",
        "points": 10,
    },
    {
        "id": "b10",
        "difficulty": "beginner",
        "category": "SMS Safety",
        "question_en": "Your electricity bill SMS comes from the number '9845XXXXXX'. Is this suspicious?",
        "question_hi": "बिजली बिल का SMS '9845XXXXXX' नंबर से आता है। क्या यह संदिग्ध है?",
        "options": [
            {"text": "No, electricity boards use mobile numbers", "text_hi": "नहीं, बिजली विभाग मोबाइल नंबर से भेजते हैं", "is_correct": False},
            {"text": "Yes — DISCOMs use 6-character registered sender headers, not 10-digit numbers", "text_hi": "हाँ — बिजली कंपनियाँ 6 अक्षर के हेडर से भेजती हैं, 10 अंकीय नंबर से नहीं", "is_correct": True},
            {"text": "Only suspicious if from a different state code", "text_hi": "केवल तब संदिग्ध है अगर दूसरे राज्य का कोड हो", "is_correct": False},
            {"text": "Not suspicious during peak billing season", "text_hi": "बिलिंग सीजन में संदिग्ध नहीं है", "is_correct": False},
        ],
        "explanation_en": "Official organizations (banks, DISCOMs, govt) use registered 6-character TRAI sender headers (e.g., AD-MSEDCL, VK-TNEBS). A 10-digit mobile number sending utility bills is always suspicious.",
        "explanation_hi": "सरकारी संस्थाएं 6 अक्षर के TRAI हेडर से SMS भेजती हैं। 10 अंकीय मोबाइल नंबर से आई यूटिलिटी बिल नोटिस हमेशा संदिग्ध है।",
        "points": 10,
    },
    {
        "id": "b11",
        "difficulty": "beginner",
        "category": "App Safety",
        "question_en": "Someone asks you to install 'AnyDesk' or 'TeamViewer' to help with your bank account issue. What should you do?",
        "question_hi": "कोई आपसे 'AnyDesk' या 'TeamViewer' इंस्टॉल करने को कह रहा है बैंक समस्या सुलझाने के लिए। क्या करें?",
        "options": [
            {"text": "Install it — remote support is legitimate", "text_hi": "इंस्टॉल करें — रिमोट सपोर्ट ठीक है", "is_correct": False},
            {"text": "REFUSE — banks never ask for remote access to your phone", "text_hi": "मना करें — बैंक कभी रिमोट एक्सेस नहीं मांगते", "is_correct": True},
            {"text": "Install but don't share your screen", "text_hi": "इंस्टॉल करें पर स्क्रीन शेयर मत करें", "is_correct": False},
            {"text": "It's okay if the caller knows your account number", "text_hi": "ठीक है अगर कॉलर को खाता नंबर पता है", "is_correct": False},
        ],
        "explanation_en": "Screen-sharing apps give scammers complete control of your phone. They can see your bank OTPs, UPI PIN, and transfer all your money remotely. Banks NEVER need remote access.",
        "explanation_hi": "स्क्रीन शेयरिंग ऐप से धोखेबाजों को आपके फोन का पूरा नियंत्रण मिल जाता है। वे OTP और PIN देखकर सारे पैसे निकाल सकते हैं।",
        "points": 10,
    },
    {
        "id": "b12",
        "difficulty": "beginner",
        "category": "Lottery Scam",
        "question_en": "You receive a WhatsApp message: 'Congratulations! You won ₹25 lakh in the KBC Lucky Draw. Send ₹5,000 processing fee to claim.' Is this real?",
        "question_hi": "WhatsApp पर: 'बधाई! KBC में ₹25 लाख जीते। ₹5,000 प्रोसेसिंग फीस भेजें।' क्या यह सच है?",
        "options": [
            {"text": "Yes, KBC does run lucky draws", "text_hi": "हाँ, KBC लकी ड्रॉ चलाता है", "is_correct": False},
            {"text": "No — legitimate prizes never require upfront fees", "text_hi": "नहीं — असली पुरस्कार के लिए पहले पैसे नहीं देने होते", "is_correct": True},
            {"text": "Real if it came from Amitabh Bachchan's official number", "text_hi": "असली है अगर अमिताभ बच्चन के नंबर से आया हो", "is_correct": False},
            {"text": "Only check if they can prove it with a lottery ticket number", "text_hi": "केवल तब मानें अगर लॉटरी टिकट नंबर दें", "is_correct": False},
        ],
        "explanation_en": "Advance Fee Fraud: You never have to pay to receive a prize. The 'fee' is the scam — once paid, they ask for more or disappear. You also never entered this lottery.",
        "explanation_hi": "अग्रिम शुल्क धोखाधड़ी: पुरस्कार पाने के लिए कभी पैसे नहीं देने होते। यही 'फीस' असली धोखाधड़ी है।",
        "points": 10,
    },
    {
        "id": "b13",
        "difficulty": "beginner",
        "category": "Link Safety",
        "question_en": "Which of these links looks MOST SUSPICIOUS as a banking link?",
        "question_hi": "इनमें से कौन सा बैंकिंग लिंक सबसे संदिग्ध लगता है?",
        "options": [
            {"text": "https://www.sbi.co.in", "text_hi": "https://www.sbi.co.in", "is_correct": False},
            {"text": "https://onlinesbi.sbi", "text_hi": "https://onlinesbi.sbi", "is_correct": False},
            {"text": "https://sbi-kyc-update.com/verify.php", "text_hi": "https://sbi-kyc-update.com/verify.php", "is_correct": True},
            {"text": "https://retail.onlinesbi.sbi/retail/login.htm", "text_hi": "https://retail.onlinesbi.sbi/retail/login.htm", "is_correct": False},
        ],
        "explanation_en": "sbi-kyc-update.com is a fake domain designed to look like SBI. Real SBI domains are sbi.co.in or onlinesbi.sbi. Always check the exact domain before entering credentials.",
        "explanation_hi": "sbi-kyc-update.com एक नकली डोमेन है। असली SBI: sbi.co.in या onlinesbi.sbi। कभी भी पूरा डोमेन चेक करें।",
        "points": 10,
    },
    {
        "id": "b14",
        "difficulty": "beginner",
        "category": "Phone Safety",
        "question_en": "A stranger calls saying they sent you money by mistake via UPI and asks you to return it. Should you trust them?",
        "question_hi": "कोई अजनबी कहता है उसने गलती से आपको UPI पर पैसे भेज दिए और वापस मांग रहा है। क्या करें?",
        "options": [
            {"text": "Return immediately — it's the right thing to do", "text_hi": "तुरंत वापस करें — यही सही है", "is_correct": False},
            {"text": "Check your UPI app — if you received it, contact the app's dispute center; don't send to an unknown number", "text_hi": "UPI ऐप जांचें — अगर आए हों तो ऐप के डिस्प्यूट सेंटर से संपर्क करें, अजनबी को मत भेजें", "is_correct": True},
            {"text": "Return only if they verify their name", "text_hi": "केवल तब लौटाएं अगर वे अपना नाम बताएं", "is_correct": False},
            {"text": "Keep the money — finders keepers", "text_hi": "पैसे रख लें", "is_correct": False},
        ],
        "explanation_en": "Common scam: They 'send' a fake screenshot of transfer. Or they actually send money from a stolen account, get you to return it to their real account, then dispute the original transaction. Always use official channels.",
        "explanation_hi": "धोखा: नकली ट्रांसफर स्क्रीनशॉट भेजते हैं या चोरी के खाते से पैसे भेजकर अपने असली खाते में वापस मंगवाते हैं।",
        "points": 10,
    },
    {
        "id": "b15",
        "difficulty": "beginner",
        "category": "Deepfake",
        "question_en": "You receive a voice message from what sounds exactly like your family member asking for urgent money transfer. What should you do?",
        "question_hi": "परिवार के किसी सदस्य की आवाज में वॉयस मैसेज आता है जरूरी पैसों के लिए। क्या करें?",
        "options": [
            {"text": "Transfer immediately since it's a family emergency", "text_hi": "तुरंत भेजें क्योंकि परिवार की जरूरत है", "is_correct": False},
            {"text": "ALWAYS call back on their saved number to verify before sending", "text_hi": "हमेशा उनके सेव नंबर पर वापस कॉल करके पुष्टि करें", "is_correct": True},
            {"text": "Ask them to send a photo as proof", "text_hi": "सबूत के तौर पर फोटो मांगें", "is_correct": False},
            {"text": "AI voice cloning is not yet possible", "text_hi": "AI से आवाज की नकल अभी संभव नहीं है", "is_correct": False},
        ],
        "explanation_en": "AI Voice Cloning is very real in 2026. With just 3 seconds of someone's voice, scammers can clone it perfectly. Always call back on a known, trusted number to verify any emergency request.",
        "explanation_hi": "2026 में AI आवाज क्लोनिंग बहुत असली है। 3 सेकंड की आवाज से नकल बन सकती है। हमेशा सेव नंबर पर वापस कॉल करें।",
        "points": 10,
    },

    # ── INTERMEDIATE (16-30) ───────────────────────────────────────────────
    {
        "id": "i1",
        "difficulty": "intermediate",
        "category": "UPI Safety",
        "question_en": "Which of these is a valid reason to enter your UPI PIN?",
        "question_hi": "UPI PIN डालने का सही कारण कौन सा है?",
        "options": [
            {"text": "To receive ₹500 cashback from Amazon", "text_hi": "Amazon से ₹500 कैशबैक पाने के लिए", "is_correct": False},
            {"text": "To verify your account is linked correctly", "text_hi": "खाता सही से जुड़ा है इसकी जांच के लिए", "is_correct": False},
            {"text": "To SEND money to a merchant for a purchase", "text_hi": "खरीदारी के लिए किसी को पैसे भेजने के लिए", "is_correct": True},
            {"text": "To accept a UPI collect request from an unknown number", "text_hi": "अजनबी नंबर से UPI कलेक्ट रिक्वेस्ट स्वीकार करने के लिए", "is_correct": False},
        ],
        "explanation_en": "UPI PIN is ONLY for sending money — paying bills, merchants, or transfers you initiate. Never for receiving, cashback, or accepting collect requests from strangers.",
        "explanation_hi": "UPI PIN केवल पैसे भेजने के लिए — बिल पेमेंट या अपनी मर्जी से ट्रांसफर। कभी रिसीव करने या कैशबैक के लिए नहीं।",
        "points": 15,
    },
    {
        "id": "i2",
        "difficulty": "intermediate",
        "category": "Digital Arrest",
        "question_en": "A scammer impersonating a police officer says your Aadhaar was used to open a money laundering account. Which of these should you do FIRST?",
        "question_hi": "फर्जी पुलिस अधिकारी कहता है आपके आधार से मनी लॉन्ड्रिंग खाता खोला गया। सबसे पहले क्या करें?",
        "options": [
            {"text": "Transfer money to a 'safe government escrow account' as instructed", "text_hi": "सरकारी एस्क्रो खाते में पैसे ट्रांसफर करें जैसा बताया गया", "is_correct": False},
            {"text": "Hang up and call your local police station directly", "text_hi": "फोन काटें और सीधे थाने को कॉल करें", "is_correct": True},
            {"text": "Give the officer your Aadhaar OTP to verify your identity", "text_hi": "अधिकारी को आधार OTP दें पहचान सत्यापित करने के लिए", "is_correct": False},
            {"text": "Stay on the call since disconnecting is a crime", "text_hi": "कॉल बने रहें क्योंकि काटना अपराध है", "is_correct": False},
        ],
        "explanation_en": "Hang up IMMEDIATELY. No legitimate officer asks for money transfers or OTPs. Contact your local police directly. If stressed, call a trusted family member first to clear your head.",
        "explanation_hi": "तुरंत फोन काटें। कोई असली अधिकारी पैसे या OTP नहीं मांगता। सीधे थाने पर जाएं।",
        "points": 15,
    },
    {
        "id": "i3",
        "difficulty": "intermediate",
        "category": "SIM Swap",
        "question_en": "If all your calls and SMS suddenly stop working, but your network shows bars, what cyber threat might this indicate?",
        "question_hi": "अगर अचानक सभी कॉल और SMS बंद हो जाएं लेकिन नेटवर्क दिखे, तो यह किस साइबर खतरे का संकेत हो सकता है?",
        "options": [
            {"text": "Tower maintenance outage", "text_hi": "टावर मेंटेनेंस आउटेज", "is_correct": False},
            {"text": "SIM Swap attack — someone has cloned your SIM", "text_hi": "SIM स्वैप अटैक — किसी ने आपका SIM क्लोन किया है", "is_correct": True},
            {"text": "Your phone bill is overdue", "text_hi": "आपका फोन बिल बकाया है", "is_correct": False},
            {"text": "Your phone needs a restart", "text_hi": "आपके फोन को रिस्टार्ट की जरूरत है", "is_correct": False},
        ],
        "explanation_en": "SIM Swap Fraud: Scammers forge documents to port your number to a new SIM. They get all your OTPs. Call your carrier IMMEDIATELY on another phone and alert your bank.",
        "explanation_hi": "SIM स्वैप धोखाधड़ी: धोखेबाज नकली दस्तावेज से आपका नंबर नई SIM पर पोर्ट कराते हैं। तुरंत दूसरे फोन से टेलीकॉम कंपनी को कॉल करें।",
        "points": 15,
    },
    {
        "id": "i4",
        "difficulty": "intermediate",
        "category": "Investment Scam",
        "question_en": "A Telegram group 'Stock Market Experts' promises guaranteed 30% monthly returns on investments. What is this likely to be?",
        "question_hi": "Telegram ग्रुप 'Stock Market Experts' हर महीने 30% गारंटीड रिटर्न का वादा करता है। यह क्या है?",
        "options": [
            {"text": "A highly skilled investment advisory service", "text_hi": "एक कुशल निवेश सलाह सेवा", "is_correct": False},
            {"text": "Pig Butchering / Investment scam — guaranteed returns don't exist in markets", "text_hi": "पिग बुचरिंग / निवेश घोटाला — बाजार में गारंटीड रिटर्न नहीं होता", "is_correct": True},
            {"text": "A government scheme for high-income earners", "text_hi": "उच्च आय वालों के लिए सरकारी योजना", "is_correct": False},
            {"text": "Only suspicious if they ask for crypto payment", "text_hi": "केवल तब संदिग्ध है अगर क्रिप्टो भुगतान मांगें", "is_correct": False},
        ],
        "explanation_en": "Pig Butchering Scam: They build trust with small initial 'profits', then convince you to invest large sums. When you try to withdraw, they disappear. SEBI-registered advisors legally cannot guarantee returns.",
        "explanation_hi": "पिग बुचरिंग: पहले छोटे मुनाफे देते हैं, फिर बड़ा निवेश करवाते हैं। निकासी के समय गायब। SEBI-पंजीकृत सलाहकार भी गारंटीड रिटर्न का वादा नहीं कर सकते।",
        "points": 15,
    },
    {
        "id": "i5",
        "difficulty": "intermediate",
        "category": "URL Safety",
        "question_en": "Which domain is the REAL HDFC Bank website?",
        "question_hi": "HDFC बैंक की असली वेबसाइट कौन सी है?",
        "options": [
            {"text": "hdfcbank-netbanking.com", "text_hi": "hdfcbank-netbanking.com", "is_correct": False},
            {"text": "www.hdfcbank.com", "text_hi": "www.hdfcbank.com", "is_correct": True},
            {"text": "hdfc-bank-login.in", "text_hi": "hdfc-bank-login.in", "is_correct": False},
            {"text": "netbankinghdfc.org", "text_hi": "netbankinghdfc.org", "is_correct": False},
        ],
        "explanation_en": "HDFC Bank's only official domain is hdfcbank.com. Any other domain (hdfc-bank-login.in, hdfcbank-netbanking.com) is a phishing site. Always type the bank URL directly, never click email/SMS links.",
        "explanation_hi": "HDFC का एकमात्र असली डोमेन hdfcbank.com है। कोई भी अन्य डोमेन फिशिंग साइट है।",
        "points": 15,
    },
    {
        "id": "i6",
        "difficulty": "intermediate",
        "category": "Recovery",
        "question_en": "You transferred ₹50,000 to a scammer 1 hour ago. What is the MOST URGENT first action?",
        "question_hi": "1 घंटे पहले स्कैमर को ₹50,000 ट्रांसफर हो गए। सबसे पहले क्या करें?",
        "options": [
            {"text": "File a police complaint at the local station", "text_hi": "स्थानीय थाने में शिकायत दर्ज करें", "is_correct": False},
            {"text": "Call 1930 IMMEDIATELY to trigger Golden Hour account freeze", "text_hi": "गोल्डन ऑवर फ्रीज के लिए तुरंत 1930 पर कॉल करें", "is_correct": True},
            {"text": "Post about it on social media for awareness", "text_hi": "जागरूकता के लिए सोशल मीडिया पर पोस्ट करें", "is_correct": False},
            {"text": "Wait for the bank to detect and reverse it", "text_hi": "बैंक को खुद पकड़ने और रिवर्स करने का इंतजार करें", "is_correct": False},
        ],
        "explanation_en": "Golden Hour (2-3 hours): Call 1930 immediately. I4C can coordinate with all banks to freeze the recipient account before the scammer withdraws. Every minute matters.",
        "explanation_hi": "गोल्डन ऑवर (2-3 घंटे): तुरंत 1930 कॉल करें। I4C सभी बैंकों से मिलकर निकासी से पहले खाता फ्रीज करवा सकता है। हर मिनट कीमती है।",
        "points": 15,
    },
    {
        "id": "i7",
        "difficulty": "intermediate",
        "category": "Romance Scam",
        "question_en": "You've been chatting online for 2 months with someone who now has an 'emergency' and asks for ₹1 lakh. You've never met them in person. What should you do?",
        "question_hi": "2 महीने से ऑनलाइन चैट कर रहे व्यक्ति को 'आपातकाल' आ गया और ₹1 लाख चाहिए। कभी मिले नहीं। क्या करें?",
        "options": [
            {"text": "Help since you've built a strong relationship", "text_hi": "मदद करें क्योंकि रिश्ता मजबूत है", "is_correct": False},
            {"text": "It's a Romance Scam — never send money to someone you've never met in person", "text_hi": "यह रोमांस स्कैम है — जिसे कभी मिले नहीं उसे पैसे न भेजें", "is_correct": True},
            {"text": "Send half the amount as a test", "text_hi": "टेस्ट के लिए आधी रकम भेजें", "is_correct": False},
            {"text": "It's okay since they sent you photos", "text_hi": "ठीक है क्योंकि उन्होंने फोटो भेजी है", "is_correct": False},
        ],
        "explanation_en": "Honeytrap/Romance Scam: Scammers build fake emotional relationships over weeks/months before making a financial request. Photos can be stolen from real people. NEVER send money to anyone you haven't met in person.",
        "explanation_hi": "रोमांस/हनीट्रैप स्कैम: हफ्तों भावनात्मक रिश्ता बनाकर पैसे मांगते हैं। फोटो असली लोगों की चुराई हो सकती है। बिना मिले कभी पैसे न भेजें।",
        "points": 15,
    },
    {
        "id": "i8",
        "difficulty": "intermediate",
        "category": "App Safety",
        "question_en": "A link sent on WhatsApp says 'Download [BankName] Security App' as an APK file. What should you do?",
        "question_hi": "WhatsApp पर लिंक: '[BankName] Security App' APK डाउनलोड करें। क्या करें?",
        "options": [
            {"text": "Download since it's from a bank link", "text_hi": "डाउनलोड करें क्योंकि बैंक का लिंक है", "is_correct": False},
            {"text": "Delete immediately — banks never send APK files", "text_hi": "तुरंत डिलीट करें — बैंक कभी APK नहीं भेजते", "is_correct": True},
            {"text": "Download only if your phone's antivirus clears it", "text_hi": "डाउनलोड करें अगर फोन का एंटीवायरस क्लियर करे", "is_correct": False},
            {"text": "Safe if the WhatsApp sender is a known contact", "text_hi": "सुरक्षित है अगर WhatsApp सेंडर जाना-पहचाना है", "is_correct": False},
        ],
        "explanation_en": "Banks and government entities NEVER distribute software via WhatsApp APK links. These are malware that steal banking credentials, OTPs, and personal data. Only install apps from the official Play Store or App Store.",
        "explanation_hi": "बैंक कभी WhatsApp पर APK नहीं भेजते। यह मैलवेयर है जो OTP और बैंकिंग डेटा चुराता है। केवल Play Store से ऐप इंस्टॉल करें।",
        "points": 15,
    },
    {
        "id": "i9",
        "difficulty": "intermediate",
        "category": "Reporting",
        "question_en": "You receive a suspicious fraud call. Which government portal should you use to report the phone number?",
        "question_hi": "आपको संदिग्ध फ्रॉड कॉल आई। किस सरकारी पोर्टल पर नंबर रिपोर्ट करें?",
        "options": [
            {"text": "cybercrime.gov.in", "text_hi": "cybercrime.gov.in", "is_correct": False},
            {"text": "Chakshu Portal (sancharsaathi.gov.in/sfc)", "text_hi": "चक्षु पोर्टल (sancharsaathi.gov.in/sfc)", "is_correct": True},
            {"text": "TRAI Consumer Complaint Portal", "text_hi": "TRAI उपभोक्ता शिकायत पोर्टल", "is_correct": False},
            {"text": "DoT Grievance Portal", "text_hi": "DoT शिकायत पोर्टल", "is_correct": False},
        ],
        "explanation_en": "Chakshu (Sanchar Saathi) is the DoT portal specifically for reporting suspicious calls, SMS, and WhatsApp scams. cybercrime.gov.in is for financial fraud where money was lost.",
        "explanation_hi": "चक्षु (संचार साथी) DoT का पोर्टल है संदिग्ध कॉल और SMS रिपोर्ट करने के लिए। cybercrime.gov.in तब जब पैसे गए हों।",
        "points": 15,
    },
    {
        "id": "i10",
        "difficulty": "intermediate",
        "category": "Banking",
        "question_en": "A person claims to be from RBI and offers to verify your bank account's 'central blacklist status' by asking for your card number and CVV. What should you do?",
        "question_hi": "RBI का कर्मचारी बनकर 'केंद्रीय ब्लैकलिस्ट स्टेटस' जांचने के लिए कार्ड नंबर और CVV मांग रहा है। क्या करें?",
        "options": [
            {"text": "Share card details since RBI is the apex bank regulator", "text_hi": "कार्ड विवरण दें क्योंकि RBI शीर्ष नियामक है", "is_correct": False},
            {"text": "Refuse — RBI never calls individuals and asks for card details", "text_hi": "मना करें — RBI व्यक्तियों को कभी कॉल नहीं करती और कार्ड विवरण नहीं मांगती", "is_correct": True},
            {"text": "Share card number but not CVV", "text_hi": "कार्ड नंबर दें पर CVV नहीं", "is_correct": False},
            {"text": "Ask them to verify via an email first", "text_hi": "पहले ईमेल से सत्यापन करने को कहें", "is_correct": False},
        ],
        "explanation_en": "RBI NEVER calls individuals. It never asks for card numbers, CVV, OTP, or PINs. Any such call is 100% a scam. Real RBI communications are formal letters, not phone calls.",
        "explanation_hi": "RBI कभी व्यक्तियों को फोन नहीं करती। कार्ड नंबर, CVV, OTP या PIN कभी नहीं मांगती। ऐसी कॉल 100% धोखाधड़ी है।",
        "points": 15,
    },
    {
        "id": "i11",
        "difficulty": "intermediate",
        "category": "WhatsApp Safety",
        "question_en": "A WhatsApp Business account with a blue verified tick contacts you about an order issue. When should you still be cautious?",
        "question_hi": "WhatsApp Business अकाउंट ब्लू टिक के साथ ऑर्डर समस्या बताता है। फिर भी कब सतर्क रहें?",
        "options": [
            {"text": "Never — blue ticks guarantee authenticity", "text_hi": "कभी नहीं — ब्लू टिक प्रामाणिकता की गारंटी है", "is_correct": False},
            {"text": "When they ask you to share OTP, install an app, or transfer money", "text_hi": "जब OTP मांगें, ऐप इंस्टॉल करने को कहें, या पैसे ट्रांसफर करवाएं", "is_correct": True},
            {"text": "Only if they call you instead of texting", "text_hi": "केवल तब अगर टेक्स्ट की जगह कॉल करें", "is_correct": False},
            {"text": "Only if their response time is slow", "text_hi": "केवल तब अगर जवाब देर से आए", "is_correct": False},
        ],
        "explanation_en": "Blue ticks can be obtained through verification but real businesses NEVER ask for OTP, password, or money transfers via chat. Scammers impersonate verified businesses to seem trustworthy.",
        "explanation_hi": "ब्लू टिक मिल सकता है लेकिन असली कंपनियाँ कभी OTP या पैसे ट्रांसफर नहीं मांगतीं। धोखेबाज वेरिफाइड बिजनेस की नकल करते हैं।",
        "points": 15,
    },
    {
        "id": "i12",
        "difficulty": "intermediate",
        "category": "Marketplace Fraud",
        "question_en": "You're selling on OLX. A buyer sends a payment of ₹10,000 as proof, showing you a screenshot, and asks you to ship the item first. The actual payment hasn't arrived. What do you do?",
        "question_hi": "OLX पर बिक्री: खरीदार ₹10,000 की स्क्रीनशॉट भेजता है और पहले सामान भेजने को कहता है। पैसे नहीं आए। क्या करें?",
        "options": [
            {"text": "Ship the item since the screenshot proves payment", "text_hi": "सामान भेजें क्योंकि स्क्रीनशॉट से भुगतान साबित होता है", "is_correct": False},
            {"text": "NEVER ship until money is confirmed in your bank — screenshots are easily faked", "text_hi": "बैंक में पैसे आने तक कभी सामान न भेजें — स्क्रीनशॉट आसानी से नकली बन सकते हैं", "is_correct": True},
            {"text": "Accept if the screenshot has a UTR number", "text_hi": "UTR नंबर वाली स्क्रीनशॉट हो तो मान लें", "is_correct": False},
            {"text": "Ship only if they agree to COD for remaining amount", "text_hi": "बाकी राशि COD पर सहमत हों तो भेजें", "is_correct": False},
        ],
        "explanation_en": "Payment screenshots are trivially easy to fake with screenshot editors. ALWAYS verify the actual credit in your bank app before shipping. No genuine buyer will insist you ship before payment arrives.",
        "explanation_hi": "पेमेंट स्क्रीनशॉट आसानी से नकली बनाई जाती है। बैंक में क्रेडिट होने के बाद ही सामान भेजें। असली खरीदार पैसे आने से पहले सामान नहीं मांगता।",
        "points": 15,
    },
    {
        "id": "i13",
        "difficulty": "intermediate",
        "category": "Phone Safety",
        "question_en": "How can you report a spam call number to the government to help block it?",
        "question_hi": "सरकार को स्पैम कॉल नंबर रिपोर्ट करने से वह कैसे मदद करती है?",
        "options": [
            {"text": "Block on your phone — that's all you can do", "text_hi": "फोन पर ब्लॉक करें — बस यही कर सकते हैं", "is_correct": False},
            {"text": "Report via TRAI DND App or Chakshu portal — DoT can permanently disconnect the number", "text_hi": "TRAI DND ऐप या चक्षु पोर्टल पर रिपोर्ट करें — DoT नंबर स्थायी बंद कर सकता है", "is_correct": True},
            {"text": "Share the number on social media", "text_hi": "सोशल मीडिया पर नंबर शेयर करें", "is_correct": False},
            {"text": "File a complaint with your local telecom store", "text_hi": "स्थानीय टेलीकॉम स्टोर में शिकायत दर्ज करें", "is_correct": False},
        ],
        "explanation_en": "The TRAI DND App and Chakshu portal let you report spam calls directly to the Department of Telecommunications. Your report can lead to disconnection of fraudulent numbers and de-registration of telemarketers.",
        "explanation_hi": "TRAI DND ऐप और चक्षु पोर्टल से DoT को सीधे रिपोर्ट करें। इससे फर्जी नंबर बंद हो सकता है।",
        "points": 15,
    },
    {
        "id": "i14",
        "difficulty": "intermediate",
        "category": "Account Security",
        "question_en": "Which combination provides the STRONGEST protection for your net banking account?",
        "question_hi": "नेट बैंकिंग खाते के लिए सबसे मजबूत सुरक्षा कौन सी है?",
        "options": [
            {"text": "Strong password + saved in browser", "text_hi": "मजबूत पासवर्ड + ब्राउजर में सेव", "is_correct": False},
            {"text": "Password + SMS OTP (2FA) + transaction PIN + registered mobile with carrier 2FA", "text_hi": "पासवर्ड + SMS OTP + ट्रांजेक्शन PIN + कैरियर 2FA", "is_correct": True},
            {"text": "Password changed monthly", "text_hi": "हर महीने पासवर्ड बदलना", "is_correct": False},
            {"text": "Using the bank's mobile app only (not web)", "text_hi": "केवल मोबाइल ऐप का उपयोग (वेब नहीं)", "is_correct": False},
        ],
        "explanation_en": "Defense in depth: Each layer must be compromised independently. Password alone is insufficient. Enable all available 2FA layers — your mobile carrier, bank OTP, and transaction PIN.",
        "explanation_hi": "बहुस्तरीय सुरक्षा: हर परत को अलग से तोड़ना होगा। केवल पासवर्ड काफी नहीं। सभी 2FA परतें सक्षम करें।",
        "points": 15,
    },
    {
        "id": "i15",
        "difficulty": "intermediate",
        "category": "Awareness",
        "question_en": "What does the 'Golden Hour' mean in the context of cyber fraud recovery in India?",
        "question_hi": "भारत में साइबर धोखाधड़ी रिकवरी में 'गोल्डन ऑवर' का क्या मतलब है?",
        "options": [
            {"text": "The best time of day to report fraud (9 AM - 10 AM)", "text_hi": "रिपोर्ट करने का सबसे अच्छा समय (सुबह 9-10 बजे)", "is_correct": False},
            {"text": "First 2-3 hours after fraud where 1930 can freeze scammer's bank account", "text_hi": "धोखाधड़ी के बाद 2-3 घंटे जिसमें 1930 स्कैमर का खाता फ्रीज कर सकता है", "is_correct": True},
            {"text": "The 24-hour window to file a police complaint", "text_hi": "24 घंटे की विंडो पुलिस शिकायत के लिए", "is_correct": False},
            {"text": "Bank's guarantee period for refund of fraudulent transactions", "text_hi": "फर्जी ट्रांजेक्शन वापसी के लिए बैंक की गारंटी अवधि", "is_correct": False},
        ],
        "explanation_en": "The Golden Hour is the critical 2-3 hour window after fraud where the I4C/1930 system can coordinate with banks to freeze accounts before ATM withdrawal. Speed is essential.",
        "explanation_hi": "धोखाधड़ी के 2-3 घंटे बाद तक I4C/1930 बैंकों से मिलकर ATM निकासी से पहले खाता फ्रीज कर सकता है। समय बहुत कीमती है।",
        "points": 15,
    },

    # ── EXPERT (31-45) ─────────────────────────────────────────────────────
    {
        "id": "e1",
        "difficulty": "expert",
        "category": "Deepfake",
        "question_en": "Which technology makes it possible for scammers to perfectly replicate a family member's voice using only a short audio clip?",
        "question_hi": "कौन सी तकनीक से धोखेबाज केवल छोटी ऑडियो क्लिप से परिवार की आवाज की नकल कर सकते हैं?",
        "options": [
            {"text": "Voice Modulation Software", "text_hi": "वॉयस मॉड्यूलेशन सॉफ्टवेयर", "is_correct": False},
            {"text": "AI Voice Cloning using Neural TTS models (e.g. VALL-E, ElevenLabs)", "text_hi": "न्यूरल TTS मॉडल से AI वॉयस क्लोनिंग (जैसे VALL-E, ElevenLabs)", "is_correct": True},
            {"text": "Deep Packet Inspection telephony", "text_hi": "डीप पैकेट इंस्पेक्शन टेलीफोनी", "is_correct": False},
            {"text": "Phone number spoofing combined with voice filters", "text_hi": "फोन नंबर स्पूफिंग और वॉयस फिल्टर का संयोजन", "is_correct": False},
        ],
        "explanation_en": "AI Voice Cloning models like VALL-E can replicate any voice from 3 seconds of audio. ElevenLabs and similar tools are commercially available. Detection: call back on a KNOWN number with a pre-agreed code word.",
        "explanation_hi": "VALL-E जैसे AI वॉयस क्लोनिंग मॉडल केवल 3 सेकंड की ऑडियो से आवाज कॉपी कर सकते हैं। बचाव: जाने-माने नंबर पर वापस कॉल करें।",
        "points": 20,
    },
    {
        "id": "e2",
        "difficulty": "expert",
        "category": "Technical",
        "question_en": "Why is a UPI 'Collect Request' more dangerous than a regular payment QR code for potential fraud?",
        "question_hi": "UPI 'कलेक्ट रिक्वेस्ट' नियमित पेमेंट QR से ज्यादा खतरनाक क्यों है?",
        "options": [
            {"text": "It directly accesses your bank account without PIN", "text_hi": "यह बिना PIN के सीधे बैंक खाते तक पहुँचती है", "is_correct": False},
            {"text": "It can look like incoming money while actually requiring outgoing payment authorization", "text_hi": "यह आने वाले पैसे जैसी दिखती है जबकि असल में आउटगोइंग पेमेंट अनुमोदन है", "is_correct": True},
            {"text": "It bypasses bank 2FA verification completely", "text_hi": "यह बैंक 2FA जांच को पूरी तरह बायपास करती है", "is_correct": False},
            {"text": "It reveals your UPI virtual payment address to the sender", "text_hi": "यह भेजने वाले को आपका UPI वर्चुअल एड्रेस उजागर करती है", "is_correct": False},
        ],
        "explanation_en": "A UPI Collect Request appears in PhonePe/GPay as 'Someone wants to collect ₹XXXX'. Scammers frame it as a 'refund'. Approving it (with PIN) SENDS money. Never approve collect requests from strangers.",
        "explanation_hi": "UPI कलेक्ट रिक्वेस्ट 'कोई ₹XXXX चाहता है' दिखती है। धोखेबाज इसे 'रिफंड' बताते हैं। PIN से अप्रूव करने पर पैसे जाते हैं।",
        "points": 20,
    },
    {
        "id": "e3",
        "difficulty": "expert",
        "category": "Legal",
        "question_en": "Under which law can victims of cyber fraud in India seek compensation from unauthorized digital transactions?",
        "question_hi": "भारत में अनधिकृत डिजिटल ट्रांजेक्शन के लिए पीड़ित किस कानून के तहत मुआवजा मांग सकते हैं?",
        "options": [
            {"text": "Indian Penal Code Section 420 (Cheating)", "text_hi": "भारतीय दंड संहिता धारा 420 (धोखाधड़ी)", "is_correct": False},
            {"text": "RBI's Zero Liability / Limited Liability Framework (2017 Circular)", "text_hi": "RBI का शून्य दायित्व / सीमित दायित्व ढांचा (2017 सर्कुलर)", "is_correct": True},
            {"text": "Consumer Protection Act 2019", "text_hi": "उपभोक्ता संरक्षण अधिनियम 2019", "is_correct": False},
            {"text": "Information Technology Act Section 66C", "text_hi": "सूचना प्रौद्योगिकी अधिनियम धारा 66C", "is_correct": False},
        ],
        "explanation_en": "RBI's 2017 Customer Protection Circular establishes zero liability for fraudulent transactions if reported within 3 working days. Limited liability applies up to 7 days. Report to bank immediately.",
        "explanation_hi": "RBI का 2017 ग्राहक संरक्षण सर्कुलर: 3 कार्य दिवस में रिपोर्ट करने पर शून्य दायित्व। 7 दिन तक सीमित दायित्व। तुरंत बैंक को सूचित करें।",
        "points": 20,
    },
    {
        "id": "e4",
        "difficulty": "expert",
        "category": "Technical",
        "question_en": "What is 'TRAI Caller Name Presentation (CNAP)' and how does it help combat phone scams?",
        "question_hi": "'TRAI कॉलर नेम प्रेजेंटेशन (CNAP)' क्या है और यह फोन स्कैम से कैसे बचाता है?",
        "options": [
            {"text": "A system that blocks all calls from unknown numbers automatically", "text_hi": "एक सिस्टम जो अज्ञात नंबरों से कॉल ब्लॉक करता है", "is_correct": False},
            {"text": "Network-level display of caller's telecom-registered name, making spoofing visible", "text_hi": "नेटवर्क स्तर पर टेलीकॉम-पंजीकृत नाम दिखाना, जिससे स्पूफिंग दिखती है", "is_correct": True},
            {"text": "An AI system that detects scam calls using voice analysis", "text_hi": "आवाज विश्लेषण से स्कैम कॉल पहचानने वाला AI सिस्टम", "is_correct": False},
            {"text": "A government database of all verified business numbers in India", "text_hi": "भारत के सभी वेरिफाइड बिजनेस नंबरों का सरकारी डेटाबेस", "is_correct": False},
        ],
        "explanation_en": "CNAP displays the name registered with the telecom operator at the network level — not crowd-sourced like Truecaller. It makes number spoofing more visible since the displayed name won't match the scammer's claimed identity.",
        "explanation_hi": "CNAP टेलीकॉम ऑपरेटर के पास पंजीकृत नाम नेटवर्क स्तर पर दिखाता है। स्पूफिंग होने पर नाम स्कैमर के दावे से मेल नहीं खाएगा।",
        "points": 20,
    },
    {
        "id": "e5",
        "difficulty": "expert",
        "category": "Technical",
        "question_en": "What is 'Pig Butchering' scam and why is it called that?",
        "question_hi": "'पिग बुचरिंग' स्कैम क्या है और इसे ऐसा क्यों कहते हैं?",
        "options": [
            {"text": "A food delivery scam targeting farmers", "text_hi": "किसानों को निशाना बनाने वाला फूड डिलीवरी स्कैम", "is_correct": False},
            {"text": "Scammers 'fatten' victims with fake investment profits before 'slaughtering' them with total loss", "text_hi": "धोखेबाज फर्जी मुनाफे से 'मोटा' करते हैं फिर पूरा नुकसान करके 'काटते' हैं", "is_correct": True},
            {"text": "A phone scam targeting pig farmers in rural areas", "text_hi": "ग्रामीण क्षेत्रों में सुअर पालकों को निशाना बनाने वाला स्कैम", "is_correct": False},
            {"text": "A scam involving fake meat products sold online", "text_hi": "ऑनलाइन नकली मांस उत्पाद बेचने वाला स्कैम", "is_correct": False},
        ],
        "explanation_en": "Pig Butchering (杀猪盘 - Shā Zhū Pán): Originated in Chinese cybercrime. Victims are 'fattened' (trusted with fake investment gains) over weeks/months then 'slaughtered' (all money taken). Common via Telegram/WhatsApp with romantic approach.",
        "explanation_hi": "पिग बुचरिंग (杀猪盘): चीन से आया साइबर अपराध। पीड़ितों को फर्जी मुनाफे से 'मोटा' करते हैं, फिर एक बार में सारे पैसे 'काट' लेते हैं।",
        "points": 20,
    },
    {
        "id": "e6",
        "difficulty": "expert",
        "category": "Recovery",
        "question_en": "After a UPI scam, what specific information should you collect before calling 1930 to maximize chances of account freeze?",
        "question_hi": "UPI स्कैम के बाद 1930 कॉल से पहले खाता फ्रीज की संभावना बढ़ाने के लिए कौन सी जानकारी जुटाएं?",
        "options": [
            {"text": "Only the scammer's phone number", "text_hi": "केवल स्कैमर का फोन नंबर", "is_correct": False},
            {"text": "UTR/transaction ID, scammer's UPI ID/account, amount, time, and your bank details", "text_hi": "UTR/ट्रांजेक्शन ID, स्कैमर का UPI ID/खाता, राशि, समय और अपने बैंक विवरण", "is_correct": True},
            {"text": "Just the screenshot of the payment", "text_hi": "केवल पेमेंट का स्क्रीनशॉट", "is_correct": False},
            {"text": "Your Aadhaar number for identity verification", "text_hi": "पहचान के लिए आधार नंबर", "is_correct": False},
        ],
        "explanation_en": "For 1930 to freeze accounts, they need: UTR (bank reference number), recipient's UPI VPA/account number, exact amount, timestamp, your bank name. More detail = faster freeze.",
        "explanation_hi": "1930 के लिए: UTR, प्राप्तकर्ता का UPI VPA/खाता नंबर, राशि, समय, आपका बैंक नाम। जितनी ज्यादा जानकारी, उतनी तेज फ्रीजिंग।",
        "points": 20,
    },
    {
        "id": "e7",
        "difficulty": "expert",
        "category": "Technical",
        "question_en": "What is 'number spoofing' and how can you verify if an incoming call is genuinely from your bank?",
        "question_hi": "'नंबर स्पूफिंग' क्या है और कॉल सच में बैंक की है यह कैसे जांचें?",
        "options": [
            {"text": "Downloading a call verification app to check the number", "text_hi": "नंबर जांचने के लिए वेरिफिकेशन ऐप डाउनलोड करें", "is_correct": False},
            {"text": "Displaying a fake caller ID — verify by hanging up and calling the bank's official number printed on your card", "text_hi": "नकली कॉलर ID दिखाना — खुद काटकर कार्ड पर छपे नंबर पर कॉल करके जांचें", "is_correct": True},
            {"text": "Number spoofing is illegal in India and therefore rare", "text_hi": "स्पूफिंग भारत में अवैध है इसलिए दुर्लभ है", "is_correct": False},
            {"text": "Truecaller will always identify spoofed bank numbers", "text_hi": "Truecaller हमेशा स्पूफ्ड बैंक नंबर पहचान लेगा", "is_correct": False},
        ],
        "explanation_en": "Spoofing allows anyone to display any number on your phone screen, including your bank's official number. Defense: Always hang up and call back using the number on the BACK of your physical debit/credit card.",
        "explanation_hi": "स्पूफिंग से कोई भी नंबर — यहाँ तक कि बैंक का नंबर — दिखाया जा सकता है। बचाव: खुद काटें और कार्ड के पीछे छपे नंबर पर कॉल करें।",
        "points": 20,
    },
    {
        "id": "e8",
        "difficulty": "expert",
        "category": "Legal",
        "question_en": "What organization is I4C and what specific role does it play in India's cyber fraud response?",
        "question_hi": "I4C कौन सा संगठन है और भारत की साइबर धोखाधड़ी प्रतिक्रिया में इसकी क्या भूमिका है?",
        "options": [
            {"text": "India's IT security research agency under MeitY", "text_hi": "MeitY के तहत भारत की IT सुरक्षा अनुसंधान एजेंसी", "is_correct": False},
            {"text": "Indian Cyber Crime Coordination Centre under MHA — coordinates 1930 helpline and inter-bank fund freezing", "text_hi": "MHA के तहत I4C — 1930 हेल्पलाइन और अंतर-बैंक फंड फ्रीजिंग का समन्वय", "is_correct": True},
            {"text": "International Internet Crimes Consortium", "text_hi": "इंटरनेशनल इंटरनेट क्राइम्स कंसोर्टियम", "is_correct": False},
            {"text": "India's CERT-In equivalent for financial sector", "text_hi": "वित्तीय क्षेत्र के लिए भारत का CERT-In समकक्ष", "is_correct": False},
        ],
        "explanation_en": "I4C (Indian Cyber Crime Coordination Centre) under Ministry of Home Affairs operates the 1930 helpline, the cybercrime.gov.in portal, and coordinates inter-bank fund freezing during the Golden Hour.",
        "explanation_hi": "I4C (भारतीय साइबर क्राइम समन्वय केंद्र) गृह मंत्रालय के तहत 1930 हेल्पलाइन, cybercrime.gov.in और गोल्डन ऑवर में अंतर-बैंक फंड फ्रीजिंग का समन्वय करता है।",
        "points": 20,
    },
    {
        "id": "e9",
        "difficulty": "expert",
        "category": "Technical",
        "question_en": "A phishing URL uses 'www.sbi.co.in.malicious-site.com'. Why does this fool people and what's the REAL domain?",
        "question_hi": "URL: 'www.sbi.co.in.malicious-site.com' — यह लोगों को क्यों धोखा देता है और असली डोमेन क्या है?",
        "options": [
            {"text": "Real domain: sbi.co.in | Trick: subdomain makes it look like SBI at first glance", "text_hi": "असली डोमेन: malicious-site.com | चाल: SBI सब-डोमेन जैसा लगता है", "is_correct": True},
            {"text": "Real domain: sbi.co.in | This is actually a valid SBI subdomain", "text_hi": "असली डोमेन: sbi.co.in | यह SBI का वैध सब-डोमेन है", "is_correct": False},
            {"text": "Real domain: sbi.co.in.com | This is a country-code domain", "text_hi": "असली डोमेन: sbi.co.in.com | यह देश-कोड डोमेन है", "is_correct": False},
            {"text": "Both sbi.co.in and malicious-site.com are owners", "text_hi": "sbi.co.in और malicious-site.com दोनों मालिक हैं", "is_correct": False},
        ],
        "explanation_en": "Domain reading rule: The REAL domain is always the last two segments before the first single slash (www.sbi.co.in.malicious-site.com → real domain = malicious-site.com). Everything before it is a subdomain controlled by malicious-site.com.",
        "explanation_hi": "डोमेन नियम: असली डोमेन हमेशा पहले स्लैश से पहले के अंतिम दो खंड हैं (malicious-site.com)। इससे पहले सब-डोमेन है जो malicious-site.com नियंत्रित करता है।",
        "points": 20,
    },
    {
        "id": "e10",
        "difficulty": "expert",
        "category": "Prevention",
        "question_en": "What is the best way to create a 'family safety code word' to protect against deepfake voice calls?",
        "question_hi": "डीपफेक वॉयस कॉल से बचाव के लिए 'फैमिली सेफ्टी कोड वर्ड' का सबसे अच्छा तरीका क्या है?",
        "options": [
            {"text": "Use a common word anyone could guess, like 'emergency'", "text_hi": "कोई आम शब्द जैसे 'आपातकाल' का उपयोग करें", "is_correct": False},
            {"text": "Agree on a unique, random, nonsensical phrase only family knows — never share digitally", "text_hi": "एक अनोखा, बेतरतीब, अर्थहीन वाक्यांश जो केवल परिवार जाने — डिजिटल रूप से कभी न शेयर करें", "is_correct": True},
            {"text": "Use your family's anniversary date as code", "text_hi": "परिवार की सालगिरह की तारीख कोड के रूप में उपयोग करें", "is_correct": False},
            {"text": "A code word is not effective against AI voice cloning", "text_hi": "AI वॉयस क्लोनिंग के खिलाफ कोड वर्ड प्रभावी नहीं है", "is_correct": False},
        ],
        "explanation_en": "Agree on a nonsensical phrase offline (e.g., 'dancing purple elephant'). In an emergency call, ask the 'family member' for the code word. An AI clone won't know it. Never store this code digitally.",
        "explanation_hi": "ऑफलाइन एक अर्थहीन वाक्यांश तय करें (जैसे 'नाचता बैंगनी हाथी')। आपातकाल में कोड वर्ड पूछें। AI क्लोन इसे नहीं जानेगा। डिजिटल रूप से कभी स्टोर न करें।",
        "points": 20,
    },
]

# ── Quiz Badges ────────────────────────────────────────────────────────────────
QUIZ_BADGES: list[dict] = [
    {
        "id": "rookie",
        "name": "Shield Rookie",
        "name_hi": "शील्ड रूकी",
        "icon": "🔰",
        "description": "You're just getting started. Keep learning!",
        "description_hi": "आप शुरुआत कर रहे हैं। सीखते रहें!",
        "min_percent": 0,
        "max_percent": 30,
        "color": "#6b7280",
    },
    {
        "id": "spotter",
        "name": "Scam Spotter",
        "name_hi": "स्कैम स्पॉटर",
        "icon": "👁️",
        "description": "You can spot the obvious scams. Stay alert!",
        "description_hi": "आप साफ धोखाधड़ी पहचान सकते हैं। सतर्क रहें!",
        "min_percent": 30,
        "max_percent": 60,
        "color": "#f59e0b",
    },
    {
        "id": "defender",
        "name": "Digital Defender",
        "name_hi": "डिजिटल डिफेंडर",
        "icon": "🛡️",
        "description": "Solid cyber awareness. You protect yourself well!",
        "description_hi": "अच्छी साइबर जागरूकता। आप खुद की अच्छी रक्षा करते हैं!",
        "min_percent": 60,
        "max_percent": 80,
        "color": "#3b82f6",
    },
    {
        "id": "guardian",
        "name": "Cyber Guardian",
        "name_hi": "साइबर गार्जियन",
        "icon": "⚔️",
        "description": "Excellent! You're protecting your whole family!",
        "description_hi": "शानदार! आप पूरे परिवार की रक्षा कर रहे हैं!",
        "min_percent": 80,
        "max_percent": 95,
        "color": "#8b5cf6",
    },
    {
        "id": "hero",
        "name": "Golden Hour Hero",
        "name_hi": "गोल्डन ऑवर हीरो",
        "icon": "🏆",
        "description": "Perfect score! You are a cybersecurity champion!",
        "description_hi": "परफेक्ट स्कोर! आप साइबर सुरक्षा चैंपियन हैं!",
        "min_percent": 95,
        "max_percent": 100,
        "color": "#f97316",
    },
]

# ── Category Colors ────────────────────────────────────────────────────────────
CATEGORY_COLORS: dict[str, str] = {
    "UPI Safety": "#00ff88",
    "OTP Safety": "#38bdf8",
    "Digital Arrest": "#f97316",
    "SMS Safety": "#a78bfa",
    "QR Code": "#fb923c",
    "Loan Apps": "#ef4444",
    "Job Scam": "#f59e0b",
    "Call Safety": "#ec4899",
    "Emergency Numbers": "#10b981",
    "App Safety": "#6366f1",
    "Lottery Scam": "#8b5cf6",
    "Link Safety": "#0ea5e9",
    "Phone Safety": "#14b8a6",
    "Deepfake": "#dc2626",
    "Recovery": "#22c55e",
    "Investment Scam": "#f43f5e",
    "URL Safety": "#0284c7",
    "Banking": "#7c3aed",
    "Romance Scam": "#db2777",
    "WhatsApp Safety": "#16a34a",
    "Marketplace Fraud": "#b45309",
    "Reporting": "#0891b2",
    "Account Security": "#4f46e5",
    "Awareness": "#059669",
    "SIM Swap": "#be123c",
    "Legal": "#0369a1",
    "Technical": "#7e22ce",
    "Prevention": "#065f46",
}
